apiVersion: v1
kind: Service
metadata:
  name: kubernetes-springboot
spec:
  type: NodePort
  ports:
    - port: 8099
      targetPort: 8099
      nodePort: 30002
  selector:
    app: kubernetes-springboot